### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by avivbueno**
Adding a woosh sound to every new data that comes in.

### CODE REVIEW

**Comment by brendannee** [comment]
Very cool - thanks for the pull request.

* I think the sounds should be configurable with a config.json file that allows them to be turned on and off.
* The deploy scripts in your PR have some variables specific to you, these should be abstracted out into the config.json file along with the BART API key.
* I like the idea of hiding the sidebar on mobile, but I think it is useful for desktop display. 

Let me know if you want to make any of these updates, or if I should merge your PR and then make the needed updates.

**Comment by avivbueno** [comment]
Emm... sorry wrong place for pull request :)

**Comment by brendannee** [comment]
Please open a new one when you have new features!

**Comment by avivbueno** [comment]
Sure, will do. Really cool app. An update on the SFO > Antioch line is
required because of new stations.

**Pull request closed without merging**
